# Generated by Django 4.2.1 on 2023-08-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_typedecable_name_alter_typedeconnecteurs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='type_de_cable',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='type_de_connecteurs',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='TypeDeCable',
        ),
        migrations.DeleteModel(
            name='TypeDeConnecteurs',
        ),
    ]
