# Generated by Django 4.2.1 on 2023-08-29 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_typedecable_typedeconnecteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='date_field',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
