# Generated by Django 4.2.1 on 2023-09-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_chatmessage_receiver_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
