# Generated by Django 4.2.1 on 2023-09-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_simplemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplemessage',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='simplemessage',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
