# Generated by Django 4.2.1 on 2023-09-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_sectionpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectionPassword',
        ),
    ]
